services:
  sw_planets_api:
    hostname: sw_planets_api
    build: ./
    ports:
      - 5005:5005
    depends_on:
      - sw_planets_db
    environment:
      WAIT_HOSTS: sw_planets_db:3306
      SW_PLANET_API_ENV: container

  sw_planets_db:
    hostname: sw_planets_db
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
