services:
  sw_planets_api:
    build: ./
    command: sh -c "sleep 10s ; python3 ./sw_planets_api/main.py"
    depends_on:
      - sw_planets_db

  sw_planets_db:
    build: ./db/
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
